version: '3.8'
services:
  face_recognizer:
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    image: htmmhmd/face_recognition:3.1.4
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - DB_API_URL=http://db_service:5000
      - AV_LOG_LEVEL=0
      - OPENCV_FFMPEG_LOGLEVEL=0
    volumes:
      - ./:/app:ro
      - face_db_data:/data:rw
    devices:
      - /dev/video0:/dev/video0
    ipc: host
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      - db_service
      - mjpg-streamer
    networks:
      - face_net
    ports:
      - "8000:8000"
    command: ["python", "run.py", ]

  drowsiness_detector:
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    image: htmmhmd/face_recognition:3.1.4
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - AV_LOG_LEVEL=0
      - OPENCV_FFMPEG_LOGLEVEL=0
    volumes:
      - ./:/app:ro
    devices:
      - /dev/video0:/dev/video0
    ipc: host
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - face_net
    depends_on:
      - mjpg-streamer
    command: ["python", "run.py", "--enable-drowsiness", "--detector", "landmark"]

  db_service:
    # build: 
    #   context: .
    #   dockerfile: Dockerfile.db
    image: htmmhmd/face_recognition_db:3.1.4
    volumes:
      -  face_db_data:/data:rw
      - ./src/database:/app/src/database:ro
      - ./src/config:/app/src/config:ro
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - face_net
    command: ["python" ,"-m" , "src.database.api.db_api"]
    
  mjpg-streamer:
    image: htmmhmd/mjpg-streamer:latest
    ports:
      - "8080:8080"
    devices:
      - /dev/video0:/dev/video0
    environment:
      - CAMERA_DEVICE=/dev/video0
      - STREAM_PORT=8080
    restart: always
    networks:
      - face_net
    privileged: true

networks:
  face_net:
    driver: bridge

volumes:
  face_db_data:
    driver: local