version: '3.8'
services:
  face_recognizer:
    image:  htmmhmd/face_recognition:2.3.9
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - DB_API_URL=http://db_service:5000
    volumes:
      - ./:/app:ro
      - face_db_data:/data:rw
    devices:
      - /dev/video0:/dev/video0
    ipc: host
    stdin_open: true
    tty: true
    depends_on:
      - db_service
    networks:
      - face_net
    ports:
      - "8000:8000"  # If needed for your application
      - "9000:9000"

    command: ["python", "api.py"]

  db_service:
    image: htmmhmd/face_recognition_db:2.3.9
    # build: 
    #   context: .
    #   dockerfile: Dockerfile.db
    volumes:
      - face_db_data:/data:rw
    ports:
      - "5000:5000"
    networks:
      - face_net
    command: ["python", "database/db_api.py"]

networks:
  face_net:
    driver: bridge

volumes:
  face_db_data:
    driver: local